### ISSUE TITLE
WAB Authentication Failed

### ISSUE THREAD

**Issue by jfatticq** [microsoftgraph/msgraph-training-uwp#10]
I'm getting a 'WAB Authentication Failed' message. I'm using my organization account to sign in. I registered my app using the Azure Portal and I'm wondering if that's the problem, but I want to understand why if that's the case.

**Comment by jasonjoh** [comment]
Yes, this is likely the cause, though it gets a little confusing now that the Azure portal has introduced their new preview registration experience :),

Assuming you used the non-preview, then your registration is not compatible with the sample. The sample uses Azure's "v2" authentication endpoints, and the Azure portals non-preview registrations only support v1.

**Comment by jasonjoh** [comment]
Closing this due to no response. If you're still having an issue with this please let me know.
