### ISSUE TITLE
Unable To Login 

### ISSUE THREAD

**Issue by zll800** [microsoftgraph/msgraph-training-uwp#12]
After entering the Microsoft account, the following error message pops up：
We're unable to complete your request
Microsoft account is experiencing technical problems. Please try again later
(I replace YOUR_APP_ID_HERE with the Application Id I got from the App Registration Portal)

**Comment by jasonjoh** [comment]
Are you still having this issue? I just tried this with both a work account (Office 365) and a Microsoft account and didn't run into that error. It sounds like maybe an intermittent issue on the Azure login side.
