### ISSUE TITLE
Cannot Log-in

### ISSUE THREAD

**Issue by smoeller-liveid** [microsoftgraph/msgraph-training-uwp#15]
I just did what was advised in the sample download, but after I type in my email address, I get:
invalid_request: The provided value for the input parameter 'redirect_uri' is not valid. The expected value is a URI which matches a redirect URI registered for this client application.

I did not change a single line of code, so any idea what went wrong?

**Comment by jasonjoh** [comment]
Did you create an OAuth.resw file with your App ID and scopes? When you registered the application in the Azure portal, did you enable the `urn:ietf:wg:oauth:2.0:oob` redirect URI?

**Comment by smoeller-liveid** [comment]
Again, I just did what was advised during download. From what I understood, the page automatically updated the solution with the required parameters during download.
At least, it now contains a "OAuth.resw" file with both an "AppId" and "Scopes" key. The AppId is a Guid, and the Scopes value is "User.Read Calendars.Read".
Regarding the Azure portal, I unfortunately do not understand what you mean. Nothing in the sample download page ever talked about the Azure portal, so I would need some more information here to check the settings.

**Comment by jasonjoh** [comment]
Ah ok, I didn't realize you had downloaded via the Quick Start experience on the Graph site. I'll investigate.

**Comment by jasonjoh** [comment]
@smoeller-liveid thanks for reporting this bug. It seems that Azure has changed the redirect URLs they add by default, so the app registration that gets created in the quick start wizard is missing the specific redirect URL it needs!

To work around the problem, you can follow these steps to update your app registration.

1. Go to https://apps.dev.microsoft.com and login with the account you used in the quick-start download.
1. Locate the app by app ID and select it. You can get your app ID by opening the OAuth.resw file in Visual Studio.
1. When prompted to edit in the Azure Portal, choose "Not now".
1. Find the "Native Application" section, and choose "Add URI".
1. Enter "urn:ietf:wg:oauth:2.0:oob".
1. Choose "Save" at the bottom of the page.

I will follow up with the Azure team so we can get the quick-start wizard working again.

**Comment by jasonjoh** [comment]
Closing issue - instructions have been added to quickstart download
