### ISSUE TITLE
Instructions appear to be out of date or inaccurate.

### ISSUE THREAD

**Issue by Noemata** [microsoftgraph/msgraph-training-uwp#20]
While trying to follow the instructions for registering the UWP app samples, I was not able to determine how I might add the redirect URI of: urn:ietf:wg:oauth:2.0:oob

Here are the steps I followed (visually):

![image](https://user-images.githubusercontent.com/6632315/59977280-56ca1880-959d-11e9-9aa7-47361d036aba.png)

When trying to set the redirect uri I see this:

![image](https://user-images.githubusercontent.com/6632315/59977314-c93af880-959d-11e9-9b8c-5750be6cd322.png)

What am I missing.  How do I set the urn:ietf:wg:oauth:2.0:oob ???

**Comment by Noemata** [comment]
It would have been helpful to clarify exactly what needs to happen when setting the "REDIRECT URI".

You instructions for step (3) should be broken down into additional sub steps for clarity.  It also helps to annote the graphics provided.

Example:

3. Select New registration ... [change] Set the Redirect URI as shown

![image](https://user-images.githubusercontent.com/6632315/59977574-c097f180-95a0-11e9-9ba1-74dae15aafa3.png)

![image](https://user-images.githubusercontent.com/6632315/59977601-0b196e00-95a1-11e9-89e6-91a72ea2576f.png)

The above change results in a working result when performing the app registration.

**Comment by Noemata** [comment]
Just noticed the equivalent Xamarin docs don't have a broken link for a critical screenshot graphic (UWP continues to get mistreated by Microsoft):

https://github.com/microsoftgraph/msgraph-training-xamarin/tree/master/demos/03-add-msgraph

It's not lost on the community that there's been a significant emphasis on Xamarin at the expense UWP!

**Comment by jasonjoh** [comment]
@Noemata thanks for reporting the broken image. I'll get that fixed immediately.

I assure you this has nothing to do with favoring Xamarin over UWP! The Azure portal changed it's UI recently, removing the `urn` redirect as a checkbox. The steps in the README haven't been updated to reflect that, I will fix that as well. Currently it says:

> Select the Add a Redirect URI link. On the Redirect URIs page, locate the Suggested Redirect URIs for public clients (mobile, desktop) section. Select the urn:ietf:wg:oauth:2.0:oob URI, then choose Save.
