### ISSUE TITLE
Only works with 1 scope?

### ISSUE THREAD

**Issue by lukedukeus** [microsoftgraph/msgraph-training-uwp#26]
I got the sample working, but I wanted to change scopes to suite the app I am making. It works with Calendar.Read, but with no other scopes. How could I edit this sample so that It doesnt hang/ crash with other scopes?

**Comment by jasonjoh** [comment]
That's certainly not expected. When does it hang or crash? Also, did you initially run the app with just the `Calendars.Read` scope and sign in, then afterwards added new scopes?

**Comment by jasonjoh** [comment]
I just tried this on my side by adding `Mail.Read` to the scopes in OAuth.resw. I didn't get any hangs or crashes.

**Comment by lukedukeus** [comment]
If I try using User.ReadBasic.All , heres what it does: https://youtu.be/iTao04vE3lA
I am trying to see if I could use microsoft graph to let different users login to an app installed on a public machine, purchase something in app, and havee it fufilled to their account. I know that there is a pop up when you click purchase on an item, but you cannot change who you are signed in as then, and I want multiple users to use this app on a public machine.

**Comment by jasonjoh** [comment]
Are you using a personal account (outlook.com, etc) to log in? I didn't reproduce the behavior using an Office 365 account, but did with a personal account. User.ReadBasic.All isn't a valid scope for personal accounts because they're not part of a directory. My guess is the toolkit component that is being used to login doesn't handle the error back from AAD.

**Comment by lukedukeus** [comment]
oh, that makes sence. I was using a personal account. What scope would I need to use for the user to sighn in, and then when they went to purchase an iap, it would purchase it on their account, and not the account of the person who owns the windows 10 distro?

**Comment by jasonjoh** [comment]
`User.Read` would allow your app to get their profile (it's what the sample uses to get their name, email, etc.). I'm assuming that's the info you need?

**Comment by lukedukeus** [comment]
Thats what I was thinking as well, but when I use User.Read, It still asks for the pasword of the pc's user when using an iap. so I am user1@outlook.com, signed into windows, and when i launch the app, I can sign in as user2@outlook.com, but when I go to purchase the in app purchase, it asks me for the password of user1@outlook.com, and there is no way to switch the user. At first I was thinking I had the wrong scope, but now im thinking that maybe graph cant pass users credentials to the iap service?

**Comment by jasonjoh** [comment]
To be honest I don't know, but probably not? I'm not familiar with "iap". 

Graph actually doesn't provide any credentials, that's all handled by the Azure Active Directory. Graph requires an access token issued by AAD with graph.microsoft.com as the audience. That token wouldn't be compatible with any other service (unless this iap service is part of Graph).

Basically you can use Azure + Graph to establish the identity of the signed-in user (Azure authorizes and verifies the user, Graph can provide your app with details about the user from their profile), but I'm not sure how that would translate over to this other service.
