### ISSUE TITLE
Cannot sign-in

### ISSUE THREAD

**Issue by BobSeelbach** [microsoftgraph/msgraph-training-uwp#28]
Using the Quick Start (using UWP), I did all of the steps (register app, got app id, went to the azure portal, added redirect, downloaded the zip, extracted). I loaded the solution and built it (using x64). When I run it there is no "sign-in" button. I watched the video under Build UWP apps with Microsoft Graph, he shows the same app with the button and he can sign in.

Am I missing something? Do I need to go through the tutorial to manually add the underlying code?

*UPDATED* I went through the step by step guide building the application from scratch and I have the same issue at the end of Step 1. All of the code copied correctly, it builds and executes ... but *NO* "sign in" button control.

I am building using VS2017 and Win10 Enterprise 1709 Build 16299.1451 ... is this an issue for this application?

PLEASE HELP

**Comment by jasonjoh** [comment]
@BobSeelbach sorry you're having trouble! I'm not sure what would cause the control to not show up, your versions should be fine. Have you tried adding it to a blank project to see if it will render?

**Comment by BobSeelbach** [comment]
@jasonjoh Hi Jason,

Yes, as I stated in the updated portion, I went thru the step-by-step guide (Build UWP Apps with Microsoft Graph) that takes you thru building the graph-tutorial from scratch. At the end of Step 1 it instructs you to run the app in the debugger and when I do, the sign-in button control does not appear. (see attached screenshot)

![graph-tutorial screen](https://user-images.githubusercontent.com/57149675/67904416-b389a100-fb44-11e9-8538-e95299e45e61.jpg)

Just to be sure, after your reply I created a new app (TestSignIn) that just did the minimum XAML and code (commenting out anything that flagged as errors) and it still comes up without the sign-in button.

Now when in the IDE when I open a XAML I get a message in the Designer that says "Visual Studio requires a newer version of Windows to display this content. Please update to Windows 10, version 1903 (10.0.18362.0) or later." I know you said the versions shouldn't matter but I wonder?

**Comment by jasonjoh** [comment]
I believe that message just means that the designer preview functionality needs you to update, but I'm not a Visual Studio expert by any means :). If you have the ability to do so, updating couldn't hurt.

According to the [toolkit's README](https://github.com/windows-toolkit/WindowsCommunityToolkit), they support Fall Creators Update (16299) SDK so I would think it would work.

If you can't get the control to show up you might want to [post an issue](https://github.com/windows-toolkit/WindowsCommunityToolkit/issues) on their repository with the details.

**Comment by jasonjoh** [comment]
Yep, frankly I'm stumped :). Please add a link to this issue from the new issue so we can follow the resolution.
