### ISSUE TITLE
Redirect URI not matching

### ISSUE THREAD

**Issue by pro4353** [microsoftgraph/msgraph-training-uwp#31]
invalid_request: The provided value for the input parameter 'redirect_uri' is not valid. The expected value is a URI which matches a redirect URI registered for this client application.

**Comment by jasonjoh** [comment]
Did you see #15?

**Comment by sebomio** [comment]
This solution is now outdated, as you can't change app settings in apps.dev.microsoft.com.

You have to go through the Azure setup, which doesn't allow urls that do not start with 'http', making "urn:ietf:wg:oauth:2.0:oob" invalid.

I have the same issue as #15, using the Python sample redirects to a login page, which gets skipped quite fast to the error message :
invalid_request: The provided value for the input parameter 'redirect_uri' is not valid. The expected value is a URI which matches a redirect URI registered for this client application.

**Comment by jasonjoh** [comment]
@sebomio this tutorial does not have you go to apps.dev.microsoft.com, so I'm not sure what your feedback is about.

I've refreshed this tutorial for the latest version of MSAL, which does change the redirect. See the version in this branch: https://github.com/microsoftgraph/msgraph-training-uwp/tree/refresh-tutorial

**Comment by jasonjoh** [comment]
Fixed via https://github.com/microsoftgraph/msgraph-training-uwp/pull/33
