### ISSUE TITLE
error connection

### ISSUE THREAD

**Issue by PatrickKranig** [microsoftgraph/msgraph-training-uwp#34]
Hi, iam new on graoh API and UWP

when i would debug my UWP, i get the error:

DEP6957: Failed to connect to device "127.0.0.1" using universal authentication. Please ensure that the correct remote authentication mode is specified in the project's debug settings. COMException - A connection could not be established because the target computer refused to connect. (Exception from HRESULT: 0x8007274D) [0x8007274D] GraphTutorial

Please help

Kind regards

**Comment by jasonjoh** [comment]
Sorry you're having trouble @PatrickKranig! That's a new one on me, but I found some similar reports that indicate that can happen if you're building/debugging an ARM build. Check in Visual Studio and try an x86 or x64 flavor of your build:

![image](https://user-images.githubusercontent.com/8966342/80224017-21f07d00-8617-11ea-8911-4196a50fbd78.png)

**Comment by jasonjoh** [comment]
@PatrickKranig did that resolve your problem?

**Comment by PatrickKranig** [comment]
oh sorry, yeah thanks
