### ISSUE TITLE
Exception trying to authenticate - Microsoft.Graph.Auth.AuthenticationException in System.Private.CoreLib.dll

### ISSUE THREAD

**Issue by dannyp32** [microsoftgraph/msgraph-training-uwp#35]
Hi,

I tried running the sample with my own app Id and when I try to login, the window dissapears. In the debug output I see:

Exception thrown: 'Microsoft.Graph.Auth.AuthenticationException' in System.Private.CoreLib.dll

I tried using an MSA and an AAD account. It repros 100% for both accounts. Is there a workaround for this issue?

**Comment by jasonjoh** [comment]
This is not a known issue. Can you catch the exception and see if there's any more information available? What line of code throws the exception?

**Comment by dannyp32** [comment]
The debugger doesn't catch the exception. It just silently fails and shows the exception in the visual studio output

![image](https://user-images.githubusercontent.com/921928/87205922-6823b700-c2bd-11ea-9f0b-ade93f9cc39b.png)

**Comment by dannyp32** [comment]
I found that the issue was that my scopes were incorrect. 

My scopes were missing an "s" at the end of Calendars.Read
 
I had 
User.Read Calendar.Read
 
instead of 
User.Read Calendars.Read
