### ISSUE TITLE
The name 'AttendeePicker' does not exist in the current context	GraphTutorial

### ISSUE THREAD

**Issue by chanmmn** [microsoftgraph/msgraph-training-uwp#40]
**Where did you get the code?**
- [x ] Downloaded from GitHub
- [ ] Downloaded from the [Microsoft Graph quick start tool](https://developer.microsoft.com/graph/quick-start)
- [ ] Followed the tutorial from [Microsoft Graph tutorials](https://docs.microsoft.com/graph/tutorials)

**Describe the bug**
Build error: 
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0103	The name 'AttendeePicker' does not exist in the current context	GraphTutorial	D:\test\other\Graph\msgraph-training-uwp-main\demo\GraphTutorial\NewEventPage.xaml.cs	237	Active

**To Reproduce**
Build the downloaded solution. 

**Expected behavior**
Build without error. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser N/A
 - Version N/A

**Dependency versions**
 - Authentication library (MSAL, etc.) version:
 - Graph library (Graph SDK, REST library, etc.) version:  

**Additional context**

**Comment by jasonjoh** [comment]
Sorry you're having trouble with the sample. I reproduced this behavior by downloading the code as a ZIP. I cleared the error by doing **Clean Solution** and then **Rebuild Solution**. Let me know if that fixes it for you.

**Comment by chanmmn** [comment]
Yes, Clean Solution then Rebuild Solution works. Thanks and sorry for the trouble.
